(use-modules (srfi srfi-1))
(define (swap lis)
  (if (pair? lis)
    (reverse (append (reverse (cddr lis)) (list (car lis) (cadr lis)) ))
    lis))

(define результаты
'(
(история	3	отл)
(информатика	3	хор)
(физкультура	2	зач)
(линал		7	удо)
(матан		11	хор)
(физика		15	хор)
(иняз		10	отл)
(право		2	зач)
(инжграф	3	удо)
(философия	3	отл)
(дифур		3	зач)
(теорвер	3	удо)
(экономика	2	зач)
(безопасность	2	зач)
(антикоррупция	1	зач)
(процедурка	5	отл)
(ооп		5	отл)
(архвс		3	зач)
(кти		2	зач)
(аикмс		3	зач)
(пробд		4	отл)
(тоив		3	зач)
(арвр		3	отл)
(бигдата	4	зач)
(тппи		9	отл)
(введениепд	1	зач)
(матлогика	3	отл)
(тка		4	отл)
(апсу		4	отл)
(всрв		4	отл)
(элсау		3	зач)
(окто		3	хор)
(рбдрв		3	отл)
(кибфиз		8	отл)
(ост		4	зач)
(прасрв		8	отл)
(тсау		7	отл)
(атпп		4	отл)
(надежность	4	отл)
(ппса		4	отл)
(мас		3	зач)
(сау		7	отл)
(проминф	7	отл)
(пиис		3	зач)
(проминет	4	зач)
(тоап		5	отл)
(диазйн		3	зач)
(прак1		3	удо)
(прак2		15	отл)
(прак3		6	отл)
(диплом		9	отл)
))

(define (без-зачётов предметы)
  (remove
    (lambda (предмет) (eq? (caddr предмет) 'зач))
    предметы))

(define (с-зачётами предметы)
  (filter #t предметы))

(define (российская оценка)
  (let ((запись (assoc (car оценка) '((отл 5) (зач 5) (хор 4) (удо 3)))))
    (if запись (append (list (cadr запись)) (cdr оценка)) #f)))

(define (американская оценка)
  (let ((запись (assoc (car оценка) '((отл 4) (зач 4) (хор 3) (удо 2)))))
    (if запись (append (list (cadr запись)) (cdr оценка)) #f)))

(define-syntax pipe
  (syntax-rules (map)
    ((pipe data) data)
    ((pipe data map func) (map func data))
    ((pipe data map func . other_funcs) (pipe (map func data) . other_funcs ))
    ((pipe data func) (func data))
    ((pipe data func . other_funcs) (pipe (func data) . other_funcs ))
    ))

(define (displayln x) (display x) (newline))

(define (avg-weighted vals-weights)
  (let ((vals (map car vals-weights)) (weights (map cadr vals-weights)))
  (/
    (reduce + 0
      (map * vals weights))
    (reduce + 0 weights))))


(pipe результаты без-зачётов map cdr map swap map российская avg-weighted exact->inexact display)
